#!/usr/bin/env python3

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""


from setuptools import setup
#import pip
#pip.main(['install','-r','requirements.txt'])

APP = ['FactorOracleNavigator_tutorial.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
